openapi: 3.0.3
info:
  title: AVIATION API
  version: 0.0.0
paths:
  /api/aircraft/:
    get:
      operationId: aircraft_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set. Pagiinate is with 10 records
        schema:
          type: integer
      tags:
      - aircraft
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRetrieveAircraftList'
          description: ''
    post:
      operationId: aircraft_create
      tags:
      - aircraft
      requestBody:
        content:
          application/json:
            schema:
              example:
                serial_number: 407,
                manufacturer: Airforce
          application/x-www-form-urlencoded:
            schema:
              example:
                serial_number: 407,
                manufacturer: Airforce
          multipart/form-data:
            schema:
              example:
                serial_number: 407,
                manufacturer: Airforce
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAircraft'
          description: ''
  /api/aircraft/{serial_number}:
    get:
      operationId: aircraft_retrieve
      parameters:
      - in: path
        name: serial_number
        schema:
          type: string
        required: true
      tags:
      - aircraft
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAircraft'
          description: ''
    put:
      operationId: aircraft_update
      parameters:
      - in: path
        name: serial_number
        schema:
          type: string
        required: true
      tags:
      - aircraft
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrieveAircraft'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RetrieveAircraft'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RetrieveAircraft'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAircraft'
          description: ''
    patch:
      operationId: aircraft_partial_update
      parameters:
      - in: path
        name: serial_number
        schema:
          type: string
        required: true
      tags:
      - aircraft
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveAircraft'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveAircraft'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveAircraft'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAircraft'
          description: ''
  /api/flights/:
    get:
      operationId: flights_list
      parameters:
      - in: query
        name: arrival_airport
        schema:
          type: string
      - in: query
        name: departure_airport
        schema:
          type: string
      - in: query
        name: end_to
        schema:
          type: string
          format: date-time
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: start_from
        schema:
          type: string
          format: date-time
      tags:
      - flights
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRetrieveFlightsList'
          description: ''
    post:
      operationId: flights_create
      tags:
      - flights
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFlights'
          description: ''
  /api/flights/{id}:
    get:
      operationId: flights_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - flights
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFlights'
          description: ''
    put:
      operationId: flights_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - flights
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RetrieveFlights'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFlights'
          description: ''
    patch:
      operationId: flights_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - flights
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveFlights'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveFlights'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRetrieveFlights'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFlights'
          description: ''
    delete:
      operationId: flights_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - flights
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/report/:
    get:
      operationId: report_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - report
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedReportList'
          description: ''
components:
  schemas:
    PaginatedReportList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Report'
    PaginatedRetrieveAircraftList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/RetrieveAircraft'
    PaginatedRetrieveFlightsList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/RetrieveFlights'
    PatchedRetrieveAircraft:
      type: object
      properties:
        serial_number:
          type: string
        manufacturer:
          type: string
    PatchedRetrieveFlights:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        aircraft:
          allOf:
          - $ref: '#/components/schemas/RetrieveAircraft'
          readOnly: true
        departure_airport:
          allOf:
          - $ref: '#/components/schemas/RetrieveAirport'
          readOnly: true
        arrival_airport:
          allOf:
          - $ref: '#/components/schemas/RetrieveAirport'
          readOnly: true
        departure_date:
          type: string
          format: date-time
          nullable: true
        arrival_date:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
    Report:
      type: object
      properties:
        departure_airport:
          type: string
          readOnly: true
        in_flight_aircraft:
          type: string
          readOnly: true
        in_flight_minutes:
          type: string
          readOnly: true
      required:
      - departure_airport
      - in_flight_aircraft
      - in_flight_minutes
    RetrieveAircraft:
      type: object
      properties:
        serial_number:
          type: string
        manufacturer:
          type: string
      required:
      - manufacturer
      - serial_number
    RetrieveAirport:
      type: object
      properties:
        code:
          type: string
          pattern: ^[A-Z]{1}[A-Z0-9]{1,3}$
          maxLength: 4
        name:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        country:
          type: string
          nullable: true
      required:
      - code
    RetrieveFlights:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        aircraft:
          allOf:
          - $ref: '#/components/schemas/RetrieveAircraft'
          readOnly: true
        departure_airport:
          allOf:
          - $ref: '#/components/schemas/RetrieveAirport'
          readOnly: true
        arrival_airport:
          allOf:
          - $ref: '#/components/schemas/RetrieveAirport'
          readOnly: true
        departure_date:
          type: string
          format: date-time
          nullable: true
        arrival_date:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
      - aircraft
      - arrival_airport
      - departure_airport
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
