# Generated by Django 4.2.3 on 2023-07-11 13:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_serial_number', models.CharField(primary_key=True, serialize=False)),
                ('manufacurer', models.CharField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Field should be a 4 uppercase and number characters', regex='^[A-Z]{1}[A-Z0-9]{1,3}$')])),
                ('name', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviation_api.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_flights', to='aviation_api.airports')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_flights', to='aviation_api.airports')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
