# Generated by Django 4.2.3 on 2023-07-11 15:45

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aircraft',
            managers=[
                ('activeobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
