# Generated by Django 4.2.3 on 2023-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0002_alter_aircraft_managers_alter_aircraft_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(default='2023-07-11 07:59:15'),
        ),
    ]
