# Generated by Django 4.2.3 on 2023-07-11 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0003_alter_aircraft_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
