# Generated by Django 4.2.3 on 2023-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0004_alter_aircraft_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
