# Generated by Django 4.2.3 on 2023-07-11 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0006_alter_flights_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
