# Generated by Django 4.2.3 on 2023-07-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0007_flights_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='manufacurer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='aircraft_serial_number',
            new_name='serial_number',
        ),
    ]
