# Generated by Django 4.2.2 on 2023-07-13 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_api', '0008_rename_manufacurer_aircraft_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Field should be a 4 uppercase and number characters', regex='^[A-Za-z0-9]{4}$')]),
        ),
    ]
